[package]
name = "task_widget"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.21"
winit = "0.28"
dirs = "5.0"
egui_dnd = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }

